### PR TITLE
Rubocop and flay config changes

### PR DESCRIPTION
**Pull request by kbiedrzycki**
I've added schema.rb to ignored files.
Also changed BracesAroundHashParameters to require braces, context_dependent rule is quite silly, according to documentation:

```
The `context_dependent` style checks that the last parameter doesn't have braces around it, but requires braces if the second to last parameter is also a hash literal.
```

Unfortunately there's no option to allow to put empty lines around top level block (for example describe blocks), so I've added that option only to module bodies.

### CODE REVIEW

**Comment by seban** [comment]
Good change for me. 👍

**Comment by LucoLe** [comment]
Well I personally don't like the braces around hash parameters and also I don't think that the new lines make the code more readable but you can forget to add them or add two lines etc...
This is just my opinion and I would like to hear what the other think about these changes.

**Comment by valo** [comment]
Can someone provide some code snippets of the options we are discussing here?

**Comment by LucoLe** [comment]
BracesAroundHashParameters
```
create(:claim, :new, { backoffice_id: 1024 })
```

vs

```
create(:claim, :new, backoffice_id: 1024)
```

EmptyLinesAroundModuleBody / EmptyLinesAroundClassBody / EmptyLinesAroundBlockBody
```
module foo

  class bar

    def baz
      something.each do
    
        some_stuff

      end
    end

  end

end
```

vs

```
module foo
  class bar
    def baz
      something.each do
        some_stuff
      end
    end
  end
end
```

**Comment by valo** [comment]
I vote for no braces and no empty lines (essentially the second version of the examples)

**Comment by bytnar** [comment]
(voting for no change)

**Comment by LucoLe** [comment]
Please lets close this PR since it's been a more than a month since the last comment and nobody is taking any action. I vote for closing this PR and deleting the branch.

**Comment by seban** [comment]
Closing and removing branch then.

**Pull request closed without merging**
